<template>
    <header class="theme-main-menu sticky-menu theme-menu-nine pt-[60px] absolute z-[99] transition-all duration-[0.4s] ease-[ease-out] p-[20px_60px] top-0 inset-x-0 2xl:px-[35px] lg:px-5 md:px-[12px] sm:px-[12px] xsm:px-[12px] fixed_top">
        <div class="notice-banner text-center absolute text-black p-[10px_12px] top-0 inset-x-0 bg-yellow-300 lg:p-[5px_12px] lg:text-[15px] md:p-[5px_12px] md:text-[15px] sm:p-[5px_12px] sm:text-[15px] xsm:p-[5px_12px] xsm:text-[15px]">
            It's the last day to save. The skills for now — <a href="#" class="font-medium hover:text-black hover:underline underline">now on sale.</a>
        </div>
        <div class="inner-content relative">
            <div class="flex items-center justify-between">
                <div class="logo xl:order-0 lg:order-0">
                    <a 
                        href="/" 
                        class="block">
                        <img 
                            src="https://profemx.s3.amazonaws.com/public/site-assets/home/ProfeMX.png" 
                            alt="" 
                            width="93">
                    </a>
                </div>

                <form 
                    action="#" 
                    class="header-search-one relative xl:order-1 lg:order-1 mr-[auto] w-[420px] h-[45px] ml-[7.5vw] 2xl:max-w-[330px] 2xl:ml-[2.5vw] lg:max-w-[300px] lg:ml-[15px] md:m-[0_auto] md:p-[0_15px] sm:m-[0_auto] sm:p-[0_15px] xsm:m-[0_auto] xsm:p-[0_15px]">
                    <input class=" w-full h-full border text-[15px] text-black p-[0_15px_0_50px] rounded-[30px] border-solid border-black bg-transparent lg:text-[14px] lg:p-[0_12px_0_35px] md:text-[14px] md:p-[0_12px_0_35px] sm:text-[14px] sm:p-[0_12px_0_35px] xsm:text-[14px] xsm:p-[0_12px_0_35px]" type="text" placeholder="What do you want to learn today?">
                    <img
                        src="https://jano-html.ibthemespro.com/images/icon/icon_122.svg" 
                        alt="" 
                        class="icon absolute -translate-y-2/4 left-[30px] top-2/4 lg:left-[20px] md:left-[33px] sm:left-[33px] xsm:left-[33px]">
                </form>

                <div class="right-widget xxl:ml-[3rem] xl:ml-[1rem] lg:ml-[1rem] flex items-center xl:order-3 lg:order-3">
                    <a href="signin.html" class="login-btn-two font-medium hidden xl:flex lg:flex items-center mr-[1.5rem] text-[18px] text-black hover:underline">
                        <img src="https://jano-html.ibthemespro.com/images/icon/icon_121.svg" alt="" class="mr-[.5rem]">
                        <span>login</span>
                    </a>
                    <a href="signup.html" class="signup-btn-three font-medium tran3s hidden xl:block lg:block leading-[45px] tracking-[-0.36px] text-white p-[0_28px] rounded-[28px] hover:text-black bg-black hover:bg-[var(--prime-eleven)]">Register</a>
                </div> <!-- /.right-widget -->

                <nav class="navbar navbar-expand-lg md:p-0 sm:p-0 xsm:p-0 flex items-center py-2 xl:flex-nowrap xl:justify-start lg:flex-nowrap lg:justify-start xl:order-2 lg:order-2 static flex-wrap justify-between">
                    <button class="navbar-toggler text-[1.25rem] leading-none transition-shadow duration-[0.15s] ease-[ease-in-out] w-11 h-[38px] relative z-[99] block xl:hidden lg:hidden shadow-[0_15px_20px_0px_rgba(0,0,0,0.05)] p-0 border-0 rounded-[.25rem] focus:shadow-none bg-[var(--prime-two)] before:content-[''] before:absolute before:w-[26px] before:h-0.5 before:pointer-events-none before:transition-transform before:duration-[0.25s] before:origin-[50%_50%] before:left-[9px] before:top-2/4 before:bg-white after:content-[''] after:absolute after:w-[26px] after:h-0.5 after:pointer-events-none after:transition-transform after:duration-[0.25s] after:origin-[50%_50%] after:left-[9px] after:top-2/4 after:bg-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class=" absolute overflow-hidden w-[26px] h-0.5 indent-[200%] transition-opacity duration-[0.25s] -mt-px left-[9px] bg-white"></span>
                    </button>
                <div class="collapse navbar-collapse  
                basis-full grow items-center md:fixed md:bg-white md:h-screen md:max-h-screen md:overflow-y-auto md:clear-both md:w-80 md:max-w-[calc(100vw_-_60px)] md:z-[9999] md:-translate-x-full md:block md:transition-all md:duration-[0.3s] md:ease-[ease-in-out] md:p-[32px_15px_20px] md:left-0 md:top-0 md:visible
                sm:fixed sm:bg-white sm:h-screen sm:max-h-screen sm:overflow-y-auto sm:clear-both sm:w-80 sm:max-w-[calc(100vw_-_60px)] sm:z-[9999] sm:-translate-x-full sm:block sm:transition-all sm:duration-[0.3s] sm:ease-[ease-in-out] sm:p-[32px_15px_20px] sm:left-0 sm:top-0 sm:visible
                xsm:fixed xsm:bg-white xsm:h-screen xsm:max-h-screen xsm:overflow-y-auto xsm:clear-both xsm:w-80 xsm:max-w-[calc(100vw_-_60px)] xsm:z-[9999] xsm:-translate-x-full xsm:block xsm:transition-all xsm:duration-[0.3s] xsm:ease-[ease-in-out] xsm:p-[32px_15px_20px] xsm:left-0 xsm:top-0 xsm:visible" id="navbarNav">
                    <ul class="navbar-nav xl:flex-row lg:flex-row flex flex-col mb-0 pl-0">
                        <li class="block xl:hidden lg:hidden">
                                <div class="logo xl:min-w-[226px] min-h-[50px] flex items-center md:mb-[8vh] sm:mb-[8vh] xsm:mb-[8vh]">
                                    <a href="index.html" class="block"><img src="https://jano-html.ibthemespro.com/images/logo/logo_01.png" alt="" width="95"></a>
                                </div>
                            </li>
                        <li class="nav-item dropdown static md:relative sm:relative xsm:relative mega-dropdown active group">
                            <a class="nav-link visible block font-medium text-[18px] lg:text-[17px] leading-[initial] text-[var(--prime-two)] relative transition-all duration-[0.3s] ease-[ease-in-out] m-[0_26px] p-[13px_0] after:content-['\f282'] after:text-[12px] after:font-bold after:absolute after:leading-[56px] after:text-center after:inline-block after:ml-[0.255em] after:border-0 after:right-auto after:top-0 after:font-Bootstrap after:align-[0.255em] md:text-[16px] md:m-0 md:p-[13px_0] sm:text-[16px] sm:m-0 sm:p-[13px_0] xsm:text-[16px] xsm:m-0 xsm:p-[13px_0] dropdown-toggle whitespace-nowrap" href="#" role="button" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">Home</a>
                            <ul class="dropdown-menu m-0 static xl:absolute lg:absolute text-[16px] text-[#212529] text-left bg-clip-padding xl:z-[5] xl:bg-white xl:block xl:invisible xl:translate-y-[5px] xl:opacity-0 xl:min-w-[250px] xl:shadow-[0px_50px_100px_rgba(0,0,0,0.12)] xl:origin-[0_0] xl:transition-all xl:duration-[0.3s] xl:ease-[ease-out] xl:m-0 xl:p-[0_25px_15px] xl:rounded-[5px] xl:border-0 xl:top-full xl:inset-x-0 lg:z-[5] lg:bg-white lg:block lg:invisible lg:translate-y-[5px] lg:opacity-0 lg:min-w-[250px] lg:shadow-[0px_50px_100px_rgba(0,0,0,0.12)] lg:origin-[0_0] lg:transition-all lg:duration-[0.3s] lg:ease-[ease-out] lg:m-0 lg:p-[0_25px_15px] lg:rounded-[5px] lg:border-0 lg:top-full lg:inset-x-0 md:m-0 md:p-0 md:rounded-none md:border-0 md:bg-[#eefbfa] sm:m-0 sm:p-0 sm:rounded-none sm:border-0 sm:bg-[#eefbfa] xsm:m-0 xsm:p-0 xsm:rounded-none xsm:border-0 xsm:bg-[#eefbfa] group-hover:xl:opacity-100 group-hover:xl:visible group-hover:xl:translate-y-0 group-hover:lg:opacity-100 group-hover:lg:visible group-hover:lg:translate-y-0">
                            <li>
                                <div class="flex flex-wrap justify-center -mx-1">
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <a href="index.html" class="block dropdown-item text-center leading-10 p-0 text-[16px] tracking-[0px] capitalize relative transition-all duration-[0.3s] ease-[ease-in-out] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]">
                                            <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_01.jpg" alt="" class="!w-full"></span>
                                            <span class="text-[15px]">insurance</span>
                                        </a>
                                    </div>
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <a href="index-2.html" class="block dropdown-item text-center leading-10 p-0 text-[16px] tracking-[0px] capitalize relative transition-all duration-[0.3s] ease-[ease-in-out] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]">
                                            <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_02.jpg" alt="" class="!w-full"></span>
                                            <span class="text-[15px]">Sass Product</span>
                                        </a>
                                    </div>
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <a href="index-3.html" class="block dropdown-item text-center leading-10 p-0 text-[16px] tracking-[0px] capitalize relative transition-all duration-[0.3s] ease-[ease-in-out] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]">
                                            <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_03.jpg" alt="" class="!w-full"></span>
                                            <span class="text-[15px]">App Landing</span>
                                        </a>
                                    </div>
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <a href="index-4.html" class="block dropdown-item text-center leading-10 p-0 text-[16px] tracking-[0px] capitalize relative transition-all duration-[0.3s] ease-[ease-in-out] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]">
                                            <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_04.jpg" alt="" class="!w-full"></span>
                                            <span class="text-[15px]">Personal Portfolio</span>
                                        </a>
                                    </div>
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <a href="index-5.html" class="block dropdown-item text-center leading-10 p-0 text-[16px] tracking-[0px] capitalize relative transition-all duration-[0.3s] ease-[ease-in-out] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]">
                                            <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_05.jpg" alt="" class="!w-full"></span>
                                            <span class="text-[15px]">N.P. Charity</span>
                                        </a>
                                    </div>
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <a href="index-6.html" class="block dropdown-item text-center leading-10 p-0 text-[16px] tracking-[0px] capitalize relative transition-all duration-[0.3s] ease-[ease-in-out] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]">
                                            <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_06.jpg" alt="" class="!w-full"></span>
                                            <span class="text-[15px]">SEO &amp; Digital Agency</span>
                                        </a>
                                    </div>
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <a href="index-7.html" class="block dropdown-item text-center leading-10 p-0 text-[16px] tracking-[0px] capitalize relative transition-all duration-[0.3s] ease-[ease-in-out] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]">
                                            <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_07.jpg" alt="" class="!w-full"></span>
                                            <span class="text-[15px]">Web Hosting</span>
                                        </a>
                                    </div>
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <a href="index-8.html" class="block dropdown-item text-center leading-10 p-0 text-[16px] tracking-[0px] capitalize relative transition-all duration-[0.3s] ease-[ease-in-out] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]">
                                            <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_08.jpg" alt="" class="!w-full"></span>
                                            <span class="text-[15px]">Crypto</span>
                                        </a>
                                    </div>
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <a href="index-9.html" class="block dropdown-item text-center leading-10 p-0 text-[16px] tracking-[0px] capitalize relative transition-all duration-[0.3s] ease-[ease-in-out] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]">
                                            <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_09.jpg" alt="" class="!w-full"></span>
                                            <span class="text-[15px]">Lead Generation</span>
                                        </a>
                                    </div>
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <a href="index-10.html" class="block dropdown-item text-center leading-10 p-0 text-[16px] tracking-[0px] capitalize relative transition-all duration-[0.3s] ease-[ease-in-out] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]">
                                            <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_10.jpg" alt="" class="!w-full"></span>
                                            <span class="text-[15px]">Agency Modern</span>
                                        </a>
                                    </div>
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <a href="index-11.html" class="block dropdown-item text-center leading-10 p-0 text-[16px] tracking-[0px] capitalize relative transition-all duration-[0.3s] ease-[ease-in-out] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]">
                                            <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_11.jpg" alt="" class="!w-full"></span>
                                            <span class="text-[15px]">Design Agency</span>
                                        </a>
                                    </div>
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <a href="index-12.html" class="block dropdown-item text-center leading-10 p-0 text-[16px] tracking-[0px] capitalize relative transition-all duration-[0.3s] ease-[ease-in-out] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] active">
                                            <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_12.jpg" alt="" class="!w-full"></span>
                                            <span class="text-[15px]">Education</span>
                                        </a>
                                    </div>
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <a href="index-13.html" class="block dropdown-item text-center leading-10 p-0 text-[16px] tracking-[0px] capitalize relative transition-all duration-[0.3s] ease-[ease-in-out] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]">
                                            <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_13.jpg" alt="" class="!w-full"></span>
                                            <span class="text-[15px]">Real Estate</span>
                                        </a>
                                    </div>
                                    <div class="xl:w-[20%] lg:w-[20%] flex-[0_0_auto] px-1 max-w-full mt-[15px]">
                                        <span class="img-meta text-[15px] overflow-hidden block relative border shadow-[0px_7px_20px_rgba(0,0,0,0.03)] mb-[3px] rounded-[10px] border-solid border-[rgba(0,0,0,0.04)] leading-10 tracking-[0px] capitalize font-normal"><img src="https://jano-html.ibthemespro.com/images/menu/home_cs.jpg" alt="" class="!w-full"></span>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown relative mega-dropdown-md group">
                            <a class="nav-link visible block font-medium text-[18px] lg:text-[17px] leading-[initial] text-black relative transition-all duration-[0.3s] ease-[ease-in-out] m-[0_26px] p-[13px_0] after:content-['\f282'] after:text-[12px] after:font-bold after:absolute after:leading-[56px] after:text-center after:inline-block after:ml-[0.255em] after:border-0 after:right-auto after:top-0 after:font-Bootstrap after:align-[0.255em] md:text-[16px] md:m-0 md:p-[13px_0] sm:text-[16px] sm:m-0 sm:p-[13px_0] xsm:text-[16px] xsm:m-0 xsm:p-[13px_0] dropdown-toggle whitespace-nowrap" href="#" role="button" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">Pages</a>
                            <ul class=" dropdown-menu !min-w-[750px] !left-[-250px] md:min-w-full sm:min-w-full xsm:min-w-full m-0 static xl:absolute lg:absolute text-[16px] text-[#212529] text-left bg-clip-padding xl:z-[5] xl:bg-white xl:block xl:invisible xl:translate-y-[5px] xl:opacity-0 xl:shadow-[0px_50px_100px_rgba(0,0,0,0.12)] xl:origin-[0_0] xl:transition-all xl:duration-[0.3s] xl:ease-[ease-out] xl:m-0 xl:p-[0_25px_15px] xl:rounded-[5px] xl:border-0 xl:top-full xl:inset-x-0 lg:z-[5] lg:bg-white lg:block lg:invisible lg:translate-y-[5px] lg:opacity-0 lg:shadow-[0px_50px_100px_rgba(0,0,0,0.12)] lg:origin-[0_0] lg:transition-all lg:duration-[0.3s] lg:ease-[ease-out] lg:m-0 lg:p-[0_25px_15px] lg:rounded-[5px] lg:border-0 lg:top-full lg:inset-x-0 md:m-0 md:p-0 md:rounded-none md:border-0 md:bg-[#eefbfa] sm:m-0 sm:p-0 sm:rounded-none sm:border-0 sm:bg-[#eefbfa] xsm:m-0 xsm:p-0 xsm:rounded-none xsm:border-0 xsm:bg-[#eefbfa] group-hover:xl:opacity-100 group-hover:xl:visible group-hover:xl:translate-y-0 group-hover:lg:opacity-100 group-hover:lg:visible group-hover:lg:translate-y-0">
                                <li>
                                <div class="flex flex-wrap mx-[-12px]">
                                    <div class="xl:w-4/12 lg:w-4/12 w-full flex-[0_0_auto] px-[12px] max-w-full">
                                        <div class="menu-column p-[15px_0_15px] md:pb-0 sm:pb-0 xsm:pb-0">
                                            <h6 class="mega-menu-title font-medium text-[16px] text-black inline-block relative m-[15px_0_18px] md:m-[0_0_12px] sm:m-[0_0_12px] xsm:m-[0_0_12px] before:content-[''] before:absolute before:w-full before:h-0.5 before:bottom-[-5px] before:left-0 before:bg-black">Essential</h6>
                                            <ul class="style-none mega-dropdown-list">
                                                <li><a href="about-v1.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>About- insurance</span></a></li>
                                                <li><a href="about-v2.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>About- Real Estate</span></a></li>
                                                <li><a href="about-v3.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>About- Agency</span></a></li>
                                                <li><a href="about-v4.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>About- L.Generation</span></a></li>
                                                <li><a href="pricing.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Pricing</span></a></li>
                                                <li><a href="pricing-v2.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Pricing- Sass Product</span></a></li>
                                                <li><a href="pricing-v3.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Pricing- Web Hosting</span></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="xl:w-4/12 lg:w-4/12 w-full flex-[0_0_auto] px-[12px] max-w-full">
                                        <div class="menu-column p-[15px_0_15px] md:pb-0 sm:pb-0 xsm:pb-0">
                                            <h6 class="mega-menu-title font-medium text-[16px] text-black inline-block relative m-[15px_0_18px] md:m-[0_0_12px] sm:m-[0_0_12px] xsm:m-[0_0_12px] before:content-[''] before:absolute before:w-full before:h-0.5 before:bottom-[-5px] before:left-0 before:bg-black">Features</h6>
                                            <ul class="style-none mega-dropdown-list">
                                                <li><a href="feature(sass).html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Feature- Sass Product</span></a></li>
                                                <li><a href="feature(web-hosting).html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Feature- Web Hosting</span></a></li>
                                                <li><a href="service-v1.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Service- insurance</span></a></li>
                                                <li><a href="service-v2.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Service- Real Estate</span></a></li>
                                                <li><a href="service-v3.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Service- L.Generation</span></a></li>
                                                <li><a href="service-v4.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Service- Agency</span></a></li>
                                                <li><a href="service-details.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Service Details</span></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="xl:w-4/12 lg:w-4/12 w-full flex-[0_0_auto] px-[12px] max-w-full">
                                        <div class="menu-column p-[15px_0_15px] md:pb-0 sm:pb-0 xsm:pb-0">
                                            <h6 class="mega-menu-title font-medium text-[16px] text-black inline-block relative m-[15px_0_18px] md:m-[0_0_12px] sm:m-[0_0_12px] xsm:m-[0_0_12px] before:content-[''] before:absolute before:w-full before:h-0.5 before:bottom-[-5px] before:left-0 before:bg-black">Others</h6>
                                            <ul class="style-none mega-dropdown-list">
                                                <li><a href="testimonial.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Testimonials</span></a></li>
                                                <li><a href="team-v1.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Team One</span></a></li>
                                                <li><a href="team-v2.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Team Two</span></a></li>
                                                <li><a href="faq.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>FAQ</span></a></li>
                                                <li><a href="signin.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Signin</span></a></li>
                                                <li><a href="signup.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>Signup</span></a></li>
                                                <li><a href="404.html" class=" dropdown-item tracking-[0px] capitalize leading-[40px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-0 bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] md:text-[15px] md:leading-[42px] md:p-[0_10px] sm:text-[15px] sm:leading-[42px] sm:p-[0_10px] xsm:text-[15px] xsm:leading-[42px] xsm:p-[0_10px]"><span>404 Error</span></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown relative group">
                            <a class="nav-link visible block font-medium text-[18px] lg:text-[17px] leading-[initial] text-black relative transition-all duration-[0.3s] ease-[ease-in-out] m-[0_26px] p-[13px_0] after:content-['\f282'] after:text-[12px] after:font-bold after:absolute after:leading-[56px] after:text-center after:inline-block after:ml-[0.255em] after:border-0 after:right-auto after:top-0 after:font-Bootstrap after:align-[0.255em] md:text-[16px] md:m-0 md:p-[13px_0] sm:text-[16px] sm:m-0 sm:p-[13px_0] xsm:text-[16px] xsm:m-0 xsm:p-[13px_0] dropdown-toggle whitespace-nowrap" href="#" role="button" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">Portfolio</a>
                            <ul class="dropdown-menu static xl:absolute lg:absolute text-[16px] text-[#212529] text-left bg-clip-padding xl:z-[5] xl:bg-white xl:block xl:invisible xl:translate-y-[5px] xl:opacity-0 xl:min-w-[250px] xl:shadow-[0px_50px_100px_rgba(0,0,0,0.12)] xl:origin-[0_0] xl:transition-all xl:duration-[0.3s] xl:ease-[ease-out] xl:m-0 xl:px-[5px] xl:py-2.5 xl:rounded-[5px] xl:border-0 xl:top-full xl:inset-x-0 lg:z-[5] lg:bg-white lg:block lg:invisible lg:translate-y-[5px] lg:opacity-0 lg:min-w-[250px] lg:shadow-[0px_50px_100px_rgba(0,0,0,0.12)] lg:origin-[0_0] lg:transition-all lg:duration-[0.3s] lg:ease-[ease-out] lg:m-0 lg:px-[5px] lg:py-2.5 lg:rounded-[5px] lg:border-0 lg:top-full lg:inset-x-0 md:m-0 md:p-0 md:rounded-none md:border-0 md:bg-[#eefbfa] sm:m-0 sm:p-0 sm:rounded-none sm:border-0 sm:bg-[#eefbfa] xsm:m-0 xsm:p-0 xsm:rounded-none xsm:border-0 xsm:bg-[#eefbfa] group-hover:xl:opacity-100 group-hover:xl:visible group-hover:xl:translate-y-0 group-hover:lg:opacity-100 group-hover:lg:visible group-hover:lg:translate-y-0">
                            <li><a href="portfolio-v1.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Portfolio 01</span></a></li>
                            <li><a href="portfolio-v2.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Portfolio 02</span></a></li>
                            <li><a href="portfolio-v3.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Portfolio 03</span></a></li>
                            <li><a href="portfolio-v4.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Portfolio 04</span></a></li>
                            <li><a href="portfolio-v5.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Portfolio 05</span></a></li>
                            <li><a href="portfolio-v6.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Portfolio 06</span></a></li>
                            <li><a href="portfolio-v7.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Portfolio 07</span></a></li>
                            <li class="dropdown-submenu dropdown relative group/second">
                                <a class="dropdown-item dropdown-toggle whitespace-nowrap text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)] after:content-['\f285'] after:block after:text-inherit after:w-auto after:h-auto after:leading-[44px] after:font-bold after:text-[11px] after:transition-transform after:duration-[0.3s] after:ease-[ease-in-out] after:absolute after:text-center after:border-[none] after:right-[15px] after:top-0 after:font-Bootstrap after:bg-transparent group-hover/second:after:rotate-90" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false" href="#"><span>Single Portfolio</span></a>
                                <ul class="dropdown-menu xl:min-w-[240px] xl:shadow-[0_20px_30px_-10px_rgb(0,0,0,0.15)] xl:translate-y-0 xl:left-[calc(100%_+_5px)] xl:right-auto xl:top-0 lg:min-w-[240px] lg:shadow-[0_20px_30px_-10px_rgb(0,0,0,0.15)] lg:translate-y-0 lg:left-[calc(100%_+_5px)] lg:right-auto lg:top-0 static xl:absolute lg:absolute text-[16px] text-[#212529] text-left bg-clip-padding xl:z-[5] xl:bg-white xl:block xl:invisible xl:opacity-0 xl:origin-[0_0] xl:transition-all xl:duration-[0.3s] xl:ease-[ease-out] xl:m-0 xl:px-[5px] xl:py-2.5 xl:rounded-[5px] xl:border-0 xl:inset-x-0 lg:z-[5] lg:bg-white lg:block lg:invisible lg:opacity-0 lg:origin-[0_0] lg:transition-all lg:duration-[0.3s] lg:ease-[ease-out] lg:m-0 lg:px-[5px] lg:py-2.5 lg:rounded-[5px] lg:border-0 lg:inset-x-0 md:m-0 md:p-0 md:rounded-none md:border-0 md:bg-[#eefbfa] sm:m-0 sm:p-0 sm:rounded-none sm:border-0 sm:bg-[#eefbfa] xsm:m-0 xsm:p-0 xsm:rounded-none xsm:border-0 xsm:bg-[#eefbfa] group-hover/second:opacity-100 group-hover/second:visible group-hover/second:translate-y-0">
                                    <li><a href="portfolio-details-v1.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Portfolio details One</span></a></li>
                                    <li><a href="portfolio-details-v2.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Portfolio details Two</span></a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                        <li class="nav-item dropdown relative group">
                            <a class="nav-link visible block font-medium text-[18px] lg:text-[17px] leading-[initial] text-black relative transition-all duration-[0.3s] ease-[ease-in-out] m-[0_26px] p-[13px_0] after:content-['\f282'] after:text-[12px] after:font-bold after:absolute after:leading-[56px] after:text-center after:inline-block after:ml-[0.255em] after:border-0 after:right-auto after:top-0 after:font-Bootstrap after:align-[0.255em] md:text-[16px] md:m-0 md:p-[13px_0] sm:text-[16px] sm:m-0 sm:p-[13px_0] xsm:text-[16px] xsm:m-0 xsm:p-[13px_0] dropdown-toggle whitespace-nowrap" href="#" role="button" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">Blog</a>
                        <ul class="dropdown-menu static xl:absolute lg:absolute text-[16px] text-[#212529] text-left bg-clip-padding xl:z-[5] xl:bg-white xl:block xl:invisible xl:translate-y-[5px] xl:opacity-0 xl:min-w-[250px] xl:shadow-[0px_50px_100px_rgba(0,0,0,0.12)] xl:origin-[0_0] xl:transition-all xl:duration-[0.3s] xl:ease-[ease-out] xl:m-0 xl:px-[5px] xl:py-2.5 xl:rounded-[5px] xl:border-0 xl:top-full xl:inset-x-0 lg:z-[5] lg:bg-white lg:block lg:invisible lg:translate-y-[5px] lg:opacity-0 lg:min-w-[250px] lg:shadow-[0px_50px_100px_rgba(0,0,0,0.12)] lg:origin-[0_0] lg:transition-all lg:duration-[0.3s] lg:ease-[ease-out] lg:m-0 lg:px-[5px] lg:py-2.5 lg:rounded-[5px] lg:border-0 lg:top-full lg:inset-x-0 md:m-0 md:p-0 md:rounded-none md:border-0 md:bg-[#eefbfa] sm:m-0 sm:p-0 sm:rounded-none sm:border-0 sm:bg-[#eefbfa] xsm:m-0 xsm:p-0 xsm:rounded-none xsm:border-0 xsm:bg-[#eefbfa] group-hover:xl:opacity-100 group-hover:xl:visible group-hover:xl:translate-y-0 group-hover:lg:opacity-100 group-hover:lg:visible group-hover:lg:translate-y-0">
                            <li><a href="blog-v1.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>List With sidebar</span></a></li>
                            <li><a href="blog-v2.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Grid With sidebar</span></a></li>
                            <li><a href="blog-v3.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Grid Layout</span></a></li>
                            <li><a href="blog-details.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Blog Details</span></a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown relative group">
                            <a class="nav-link visible block font-medium text-[18px] lg:text-[17px] leading-[initial] text-black relative transition-all duration-[0.3s] ease-[ease-in-out] m-[0_26px] p-[13px_0] after:content-['\f282'] after:text-[12px] after:font-bold after:absolute after:leading-[56px] after:text-center after:inline-block after:ml-[0.255em] after:border-0 after:right-auto after:top-0 after:font-Bootstrap after:align-[0.255em] md:text-[16px] md:m-0 md:p-[13px_0] sm:text-[16px] sm:m-0 sm:p-[13px_0] xsm:text-[16px] xsm:m-0 xsm:p-[13px_0] dropdown-toggle whitespace-nowrap" href="#" role="button" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">Contact</a>
                        <ul class="dropdown-menu static xl:absolute lg:absolute text-[16px] text-[#212529] text-left bg-clip-padding xl:z-[5] xl:bg-white xl:block xl:invisible xl:translate-y-[5px] xl:opacity-0 xl:min-w-[250px] xl:shadow-[0px_50px_100px_rgba(0,0,0,0.12)] xl:origin-[0_0] xl:transition-all xl:duration-[0.3s] xl:ease-[ease-out] xl:m-0 xl:px-[5px] xl:py-2.5 xl:rounded-[5px] xl:border-0 xl:top-full xl:inset-x-0 lg:z-[5] lg:bg-white lg:block lg:invisible lg:translate-y-[5px] lg:opacity-0 lg:min-w-[250px] lg:shadow-[0px_50px_100px_rgba(0,0,0,0.12)] lg:origin-[0_0] lg:transition-all lg:duration-[0.3s] lg:ease-[ease-out] lg:m-0 lg:px-[5px] lg:py-2.5 lg:rounded-[5px] lg:border-0 lg:top-full lg:inset-x-0 md:m-0 md:p-0 md:rounded-none md:border-0 md:bg-[#eefbfa] sm:m-0 sm:p-0 sm:rounded-none sm:border-0 sm:bg-[#eefbfa] xsm:m-0 xsm:p-0 xsm:rounded-none xsm:border-0 xsm:bg-[#eefbfa] group-hover:xl:opacity-100 group-hover:xl:visible group-hover:xl:translate-y-0 group-hover:lg:opacity-100 group-hover:lg:visible group-hover:lg:translate-y-0">
                            <li><a href="contact-us.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Contact- insurance</span></a></li>
                            <li><a href="contact-us-v2.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Contact- Agency</span></a></li>
                            <li><a href="contact-us-v3.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Contact- Web Hosting</span></a></li>
                            <li><a href="contact-us-v4.html" class="dropdown-item text-[16px] tracking-[0px] capitalize leading-[44px] text-black inline-block relative transition-all duration-[0.3s] ease-[ease-in-out] p-[0_15px] bg-transparent w-full clear-both font-normal border-0 hover:text-[var(--prime-two)]"><span>Contact- L.Generation</span></a></li>
                        </ul>
                    </li>
                    </ul>
                    <!-- Mobile Content -->
                    <div class="mobile-content block xl:hidden lg:hidden">
                        <div class="flex flex-col  items-center justify-center mt-[70px]">
                            
                    <a href="signin.html" class="login-btn-two font-medium flex items-center mr-[1.5rem] text-[18px] text-black hover:underline">
                        <img src="https://jano-html.ibthemespro.com/images/icon/icon_121.svg" alt="" class="mr-[.5rem]">
                        <span>login</span>
                    </a>
                    <a href="signup.html" class="signup-btn-three font-medium tran3s leading-[45px] tracking-[-0.36px] text-white p-[0_28px] rounded-[28px] hover:text-black bg-black hover:bg-[var(--prime-eleven)]">Sign Up</a>
                        </div>
                    </div> <!-- /.mobile-content -->
                </div>
                </nav>
            </div>
        </div> <!-- /.inner-content -->
    </header>
</template>